### ISSUE TITLE
modifying bitcoinj micro payment channels

### ISSUE THREAD

**Issue by samnet** [adonley/BMesh#2]
Hello,

can you re-explain your motivations for modifying the `bitcoinJ` part on payment channels please? 
I m v. interested in setting a MPC with `bitcoinJ` on one side and some other library on the other (perhaps `pybitcointools`) and I worry about interoperability.  
If interoperability was a significant difficulty, would not it have been easier to set-up MPC facilities over TCP from scratch (e.g., using `pybitcointools` on both sides and  communicating via JSON over TCP)
(It's my first year studying CS) 

Regards,

**Comment by adonley** [comment]
At the time (I no longer know if this is the case) there wasn't a standard for micropayment channels established. bitcoinJ was basically the only functioning implementation that was around. We wanted to use a javascript library and websockets to communicate with browser clients to achieve full duplex which required some changes bitcoinJ and bitcore. Also, it's worth noting [BIP65](https://github.com/bitcoin/bips/blob/master/bip-0065.mediawiki) wasn't around either. @snakecharmer1024 was the real power behind the micropayment channels - he might be able to speak to your question better than I.

**Comment by illuzen** [comment]
Hey @samnet, thanks for your interest in Bitmesh!

Interoperability was precisely the reason we chose to modify them. Bitmesh has a javascript frontend, which uses bitcore. Bitcore at the time had a mostly functioning implementation of MPC that used P2SH and bitcoinj used raw multisig. These are not compatible, so I made bitcoinj's MPC into a P2SH version and modified bitcore's conversation structure to make them compatible.

In retrospect MPC may have been a solution looking for a problem. You can't do javascript MPCs on a mobile device because the javascript won't run while you have another tab open. It's a cool technology, but it's not really necessary to Bitmesh and makes it a lot more complicated. 

Does that answer your question?

**Comment by ilkerbrz** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
akiopro, @dionyziz, @VictorGob, @gungunfebrianza, @zoln, @xhw1, @bellangerclement, @ddaws, @lvtraveler, @fyfirman, @hosnik, @RageHardrack, @Siddhant, @LazyJoke, @OverNothing, @freddyli7, @larryyangsen, @Yothgewalt, @andrewdamelio, @centrodph
